SUP-170 | @rebeccahongsf | theme and style book details for responsive
SU-SWS/press-nextjs pull request #14
Opened 2024-06-19 01:36 UTC by rebeccahongsf

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Urgency
- How urgent is this? (Normal, High)

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to...
4. Verify...

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2024-06-24 22:00 UTC, pookmish requested changes

2024-06-24 22:00 UTC, pookmish commented on src/components/nodes/pages/sup-book/sup-book-page.tsx
> +import BookPrecart from "./book-precart"
We should use `@` paths as much as we can.

2024-06-24 22:00 UTC, pookmish commented on src/components/nodes/pages/sup-book/book-precart.tsx
> +            <div className="block min-w-fit flex-1 cursor-pointer">
Needs to be `<label>`

2024-06-24 22:00 UTC, pookmish commented on src/components/nodes/pages/sup-book/sup-book-page.tsx
> +      <div>
do you need the div if it has no classes or anything?

2024-06-24 22:00 UTC, pookmish commented on src/components/nodes/pages/sup-book/sup-book-page.tsx
> +            <div className="mb-16 hidden w-8/12 flex-col sm:flex md:hidden">
can you remove the `sm:` on the flex. It doesn't really provide any changes.

2024-06-24 22:00 UTC, pookmish commented on src/components/nodes/pages/sup-book/sup-book-page.tsx
> +                <div className="rs-mb-2 order-first">
Optionally, you could put these classes on the link.

2024-06-24 22:00 UTC, pookmish commented on src/components/nodes/pages/sup-book/sup-book-page.tsx
> +                  <H1 className="type-3 mb-0">{node.title}</H1>
I am concerned about double `h1` tags. we will want to watch this closely.

2024-06-24 22:00 UTC, pookmish commented on src/components/nodes/pages/sup-book/sup-book-page.tsx
> +                    <div className="rs-mb-2 order-first">
Optionally put classes on the link.

2024-06-24 22:00 UTC, pookmish commented on src/components/nodes/pages/sup-book/sup-book-page.tsx
> +                    {new Date(node.supBookPubDateCloth.time).toLocaleDateString("en-us", {
do you need to multiply by 1000?

2024-06-24 22:00 UTC, pookmish commented on src/components/nodes/pages/sup-book/sup-book-page.tsx
> +                  <div>Also Available from</div>
Heading?

2024-06-26 00:57 UTC, rebeccahongsf commented on src/components/nodes/pages/sup-book/sup-book-page.tsx
> +            <div className="mb-16 hidden w-8/12 flex-col sm:flex md:hidden">
We need the `sm:` on the flex to hide the book title, subtitle, and authoring information for `xs` screens 😃 
![image](https://github.com/SU-SWS/press-nextjs/assets/34019925/64cca26c-73f6-4e8c-a18d-9beab7833b59)

2024-06-26 01:00 UTC, rebeccahongsf commented on src/components/nodes/pages/sup-book/sup-book-page.tsx
> +                    {new Date(node.supBookPubDateCloth.time).toLocaleDateString("en-us", {
I don't believe we need to multiply the time since the Date Time conversion is handled within `toLocaleDateString()` 🤔

2024-06-26 15:00 UTC, pookmish commented on src/components/nodes/pages/sup-book/sup-book-page.tsx
> +            <div className="mb-16 hidden w-8/12 flex-col sm:flex md:hidden">
Oh, i didn't notice the `hidden` before it.

2024-06-26 15:03 UTC, pookmish commented on src/components/nodes/pages/sup-book/sup-book-page.tsx
> +import Heading, {H1, H2, H3} from "@components/elements/headers"
unused `Heading`

2024-06-26 15:03 UTC, pookmish commented on src/components/nodes/pages/sup-book/sup-book-page.tsx
> +                    {new Date(node.supBookPubDateCloth.time).toLocaleDateString("en-us", {
oh ok, it's not a epoch timestamp, it's a string like `2010-10-06T00:00:00+00:00` Keep in mind that some fields return a second timestamp. In those cases you have to multiply by 1000.

2024-06-26 15:03 UTC, pookmish commented on src/components/nodes/pages/sup-book/sup-book-page.tsx
> +import Heading, {H1, H2, H3} from "@components/elements/headers"
I'll remove it real quick.

2024-06-26 15:21 UTC, merged