SUP-171 SUP-173 | @rebeccahongsf | adjust book teaser spacing and book list responsive display
SU-SWS/press-nextjs pull request #17
Opened 2024-06-25 15:04 UTC by rebeccahongsf

# READY FOR REVIEW

# Summary
- adjust book teaser spacing
- adjust book list responsive display
- add left and right arrows for pagination

# Review By (Date)
- When possible

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Spin up local
3. Navigate to books page
4. Verify that the book teaser card appears the same as the [mock](https://www.figma.com/design/KSANrYJp8TW671KCamn3Dg/SU-Press-Redesign?node-id=2531-74724&t=QHzwcAvQHUfgcJew-1)
5. Verify that the book list displays the same on different breakpoints as outlined in the [components mock](https://www.figma.com/design/KSANrYJp8TW671KCamn3Dg/SU-Press-Redesign?node-id=2980-63932&t=Zfw8dtYuMlmL9VC0-1) and [books landing page mock](https://www.figma.com/design/KSANrYJp8TW671KCamn3Dg/SU-Press-Redesign?node-id=2980-50866&t=Zfw8dtYuMlmL9VC0-1)
6. Verify that the pagination appears like the mock and functions correctly.
7. Review code

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

# Associated Issues and/or People
- SUP-171

2024-06-26 14:59 UTC, pookmish requested changes

2024-06-26 14:59 UTC, pookmish commented on src/components/elements/paged-list.tsx
> +          {page === "leftArrow" ? <ArrowLongLeftIcon width={30} /> : page === "rightArrow" ? <ArrowLongRightIcon width={30} /> : page}
Let's break this into two conditional rendering. I find else rendering difficult to read.

2024-06-26 14:59 UTC, pookmish commented on src/components/patterns/hero-banner.tsx
> +      <div className="@6xl:aspect-auto relative aspect-[16/9] w-full bg-cool-grey xl:absolute @6xl:h-full">
Any particular reason to use the window instead of container breakpoints? There's now container and window breakpoints in these classes.

2024-06-26 14:59 UTC, pookmish commented on src/components/views/sup-books/book-list-view.tsx
> +          "list-unstyled grid sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 gap-20",
Why window instead of containers?

2024-06-26 14:59 UTC, pookmish commented on src/lib/hooks/usePagination.tsx
> +    const totalPageCount = Math.ceil(totalCount / pageSize);
Looks like prettier isn't doing what it's supposed to. make sure you run `yarn install` or `git config --local core.hooksPath .githooks/`. You will only need to run the latter once.

You can run prettier directly on a file by `./node_modules/.bin/prettier --ignore-unknown --write [path/to/file]`

2024-06-26 14:59 UTC, pookmish commented on src/components/elements/paged-list.tsx
> +          {page === "leftArrow" ? <ArrowLongLeftIcon width={30} /> : page === "rightArrow" ? <ArrowLongRightIcon width={30} /> : page}
Can you find a way to only display the first arrow if page `1` is not shown
Can you remove the last page number and display the arrow only if the last page number is not shown?
ie:

```
1 2 3 ->
<- 4 5 6 ->
<- 8 9 10
```
And don't forget the aria-current when we're on the first and last page.

2024-07-01 19:08 UTC, rebeccahongsf commented on src/components/patterns/hero-banner.tsx
> +      <div className="@6xl:aspect-auto relative aspect-[16/9] w-full bg-cool-grey xl:absolute @6xl:h-full">
Ooo, great catch! Not sure why the hero banner change was rolled into this 🤔 Must have been when I was switching between Summer and Press. I've reverted this file and will follow up more on container vs window queries in the next thread!

2024-07-01 19:11 UTC, rebeccahongsf commented on src/components/views/sup-books/book-list-view.tsx
> +          "list-unstyled grid sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 gap-20",
Ah, I took some time to read up on containers vs. window queries again. I’ve reverted this file and adjusted the container queries for different container size scenarios. Card lists are great contenders for container queries. If it were a full-width hero, then window queries would be better suited. All should be good now! 😉

2024-07-02 15:32 UTC, pookmish commented on src/components/elements/paged-list.tsx
> +          {page === "leftArrow" ? <ArrowLongLeftIcon width={30} /> : page === "rightArrow" ? <ArrowLongRightIcon width={30} /> : page}
Looks like you still have the first and last page numbers in the pager. See if you can remove "1" and "189" in this example
![image](https://github.com/SU-SWS/press-nextjs/assets/7185045/bb4ef81b-9a98-4e56-970b-ba81c770d14c)

2024-07-02 15:56 UTC, pookmish commented on src/components/elements/paged-list.tsx
> +          {page === "leftArrow" ? <ArrowLongLeftIcon width={30} /> : page === "rightArrow" ? <ArrowLongRightIcon width={30} /> : page}
@rebeccahongsf Try this snippet where you are conditionally rendering the arrows.
```  if (page === 1 && currentPage > 3) return null
  if (page === total && currentPage < total - 3) return null
  if (page === "leftArrow" && currentPage <= 3) return null
  if (page === "rightArrow" && currentPage >= total - 3) return null```

2024-07-02 16:26 UTC, merged