SUP-242 | adjust book excepts and details page styles
SU-SWS/press-nextjs pull request #23
Opened 2024-07-12 21:42 UTC by rebeccahongsf

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Urgency
- How urgent is this? (Normal, High)

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to...
4. Verify...

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2024-07-16 22:53 UTC, rebeccahongsf commented on src/components/elements/headers.tsx
> +    <h1 className={twMerge("type-4 font-medium", className)} {...props}>
@pookmish I realized while triple checking things that the headings defined for the [WYSIWYG designs](https://www.figma.com/design/KSANrYJp8TW671KCamn3Dg/SU-Press-Redesign?node-id=3529-67884&t=mgCL1qSCqKAsMQ2k-1) differ from the standard/summer headings. I did a mass fixup again and clicked through the site and reviewed the changes. We should be all set now but I might roll up some additional changes when I work on [SUP-240 digital project page ](https://stanfordits.atlassian.net/browse/SUP-240)

2024-07-17 15:35 UTC, pookmish approved these changes
Overall, this seems good. But there's a couple small fixes and then a bigger image thing

2024-07-17 15:35 UTC, pookmish commented on src/components/nodes/pages/sup-book/digital-project-page/digital-project-page.tsx
> +                <BookPageImage node={node} />
I believe they wanted to use a landscape image for the digital projects pages. Is that still the case? they emailed about it for the search results as well.

2024-07-17 15:35 UTC, pookmish commented on src/components/nodes/pages/sup-book/book-page/book-page.tsx
> +        <>
We probably don't need the fragment

2024-07-17 15:35 UTC, pookmish commented on src/components/nodes/pages/sup-book/book-page/book-page.tsx
> +        href="/books"
I'm not sure about this link path, but it'll be ok for now.

2024-07-17 15:35 UTC, pookmish commented on src/components/nodes/pages/sup-book/digital-project-page/digital-project-page.tsx
> +        <>
No need for the fragment.

2024-07-17 15:35 UTC, pookmish commented on src/components/nodes/pages/sup-book/digital-project-page/digital-project-page.tsx
> +      <article className="centered order-last" {...props}>
Normally, I prefer to put the `{...props}` on the outer most element.

2024-07-17 15:35 UTC, pookmish commented on src/components/nodes/pages/sup-book/book-page/book-page.tsx
> +      <article className="centered order-last" {...props}>
Normally, I prefer to put the `{...props}` on the outer most element.

2024-07-17 15:35 UTC, pookmish commented on src/components/nodes/pages/sup-book/digital-project-page/digital-project-page.tsx
> +                      href={`/search?${linkParamsString}`}
Optionally, you could use call `createLinkParams` directly in the href prop. Then you don't need to have a `return` and stuff.

2024-07-17 15:36 UTC, pookmish requested changes
I clicked the wrong button.

2024-07-17 16:20 UTC, rebeccahongsf commented on src/components/nodes/pages/sup-book/digital-project-page/digital-project-page.tsx
> +                <BookPageImage node={node} />
Ah. Looks like the node mapping for the image url in the Book Page Image component had changed so the images weren't displaying. As long as they have an image uploaded, it will display in its original ratio/dimensions. Do you think that would suffice?

Examples:
![image](https://github.com/user-attachments/assets/8f465545-5fb2-441d-8c45-ead101646728)

![image](https://github.com/user-attachments/assets/cab7f08b-d10d-4dcb-9395-a984b830a269)

2024-07-17 16:22 UTC, pookmish commented on src/components/nodes/pages/sup-book/digital-project-page/digital-project-page.tsx
> +                <BookPageImage node={node} />
Yeah, i actually just noticed that and committed a fix 12 minutes ago :smile:

2024-07-17 16:45 UTC, pookmish approved these changes
LGTM

2024-07-17 16:45 UTC, merged