SUP-282 SUP-283 SUP-284 | adjust book list, file upload, and image gallery
SU-SWS/press-nextjs pull request #49
Opened 2024-08-07 21:52 UTC by rebeccahongsf

# READY FOR REVIEW

# Summary
- adjust book list typography and spacing
- adjust file upload button sizing and wyswiyg secondary button styles
- add borders to image gallery image

# Review By (Date)
- When possible

# Review Tasks

## Setup tasks and/or behavior to test

1. Navigate to previews
2. Verify 
- the book list gap is 5.5rem
- 
3. Review code

# Associated Issues and/or People
- SUP-282
- SUP-283
- SUP-284

2024-08-07 22:00 UTC, pookmish requested changes

2024-08-07 22:00 UTC, pookmish commented on src/components/paragraphs/sup-file-list/file-list-paragraph.tsx
> +    <div className={twMerge("centered max-w-800", props.className)} {...props}>
put the `{...props}` before `className`. Otherwise, the className in the props will override your twMerge
```suggestion
    <div  {...props} className={twMerge("centered max-w-800", props.className)}>
```

2024-08-07 22:00 UTC, pookmish commented on src/components/paragraphs/sup-file-list/file-list-selection.tsx
> +    <div className={twMerge("centered max-w-800", props.className)} {...props}>
Same as the other
```suggestion
    <div {...props} className={twMerge("centered max-w-800", props.className)}>
```

2024-08-08 15:37 UTC, rebeccahongsf commented on src/components/paragraphs/sup-file-list/file-list-paragraph.tsx
> +    <div className={twMerge("centered max-w-800", props.className)} {...props}>
Thanks for catching this, Mike! I knew I was missing something 😮‍💨 

![image](https://github.com/user-attachments/assets/7e4aee19-a567-4ec6-ba14-8bb14f6ece23)

2024-08-08 16:16 UTC, pookmish approved these changes

2024-08-08 16:19 UTC, merged